version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: glow-nest-api
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_PATH=/data/glow_nest.db
      - ALLOWED_ORIGINS=http://localhost:5173
      - API_KEY=${API_KEY:-changeme-secret}
      - REQUIRE_AUTH_FOR_SSE=${REQUIRE_AUTH_FOR_SSE:-true}
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data:/data
      - ./cli/logs:/app/cli/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: glow-nest-frontend
    ports:
      - "5173:80"
    depends_on:
      api:
        condition: service_healthy
    environment:
      - PYTHON_API_URL=http://localhost:8080

  redis:
    image: redis:7-alpine
    container_name: glow-nest-redis
    ports:
      - "6379:6379"

  # Placeholder for future Postgres if migrating from SQLite
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     - POSTGRES_USER=glow
  #     - POSTGRES_PASSWORD=glow
  #     - POSTGRES_DB=glow
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ./pgdata:/var/lib/postgresql/data

networks:
  default:
    driver: bridge


