app = "glow-nest-frontend"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile.frontend"

[[services]]
  internal_port = 80
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
