name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Type check APIs import
        run: python -c "import fastapi, uvicorn; print('FastAPI OK')"
      - name: Lint (ruff fallback via flake8)
        run: |
          pip install flake8
          flake8 cli || true
      - name: Unit tests (Python)
        run: |
          python -m pip install pytest pytest-asyncio
          pytest -q || true

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Node deps
        run: |
          npm ci || npm install
      - name: Typecheck
        run: npm run typecheck --silent || true
      - name: Build
        env:
          PYTHON_API_URL: https://glow-nest-api.fly.dev
        run: npm run build --silent


